name: my_dictionary
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  flutter_native_splash: ^2.4.7
  get_it: ^9.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_native_splash:
  color: "#262626"
  image: assets/splash.png
  fullscreen: true

  android_12:
    color: "#262626"
    image: assets/splash.png

  ios:
    color: "#262626"
    image: assets/splash.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21